package cliente;

import javax.swing.JInternalFrame;

/**
 *
 * @author cesar
 */
public class Principal extends javax.swing.JFrame {

  public Principal() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jDesktopPaneBasicas = new javax.swing.JDesktopPane();
    jMenuBar1 = new javax.swing.JMenuBar();
    jMenu1 = new javax.swing.JMenu();
    jMenu2 = new javax.swing.JMenu();
    jMenuItemBasicas = new javax.swing.JMenuItem();
    jMenuItem1 = new javax.swing.JMenuItem();
    jMenuItemOtros = new javax.swing.JMenuItem();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    jMenu1.setText("Archivo");
    jMenuBar1.add(jMenu1);

    jMenu2.setText("Operaciones");

    jMenuItemBasicas.setText("Basicas");
    jMenuItemBasicas.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jMenuItemBasicasActionPerformed(evt);
      }
    });
    jMenu2.add(jMenuItemBasicas);

    jMenuItem1.setText("Probabilidad");
    jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jMenuItem1ActionPerformed(evt);
      }
    });
    jMenu2.add(jMenuItem1);

    jMenuItemOtros.setText("Otros");
    jMenuItemOtros.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jMenuItemOtrosActionPerformed(evt);
      }
    });
    jMenu2.add(jMenuItemOtros);

    jMenuBar1.add(jMenu2);

    setJMenuBar(jMenuBar1);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jDesktopPaneBasicas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jDesktopPaneBasicas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void jMenuItemBasicasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemBasicasActionPerformed
    quitarFrames();
    OperacionesBasicas ob = new OperacionesBasicas();
    ob.setName("opBasicas");    

    jDesktopPaneBasicas.add(ob);
    ob.setVisible(true);
  }//GEN-LAST:event_jMenuItemBasicasActionPerformed

  private void jMenuItemOtrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemOtrosActionPerformed
    quitarFrames();
    OperacionesOtras oo = new OperacionesOtras();
    oo.setName("opOtras");
    
    jDesktopPaneBasicas.add(oo);
    oo.setVisible(true);
  }//GEN-LAST:event_jMenuItemOtrosActionPerformed

  private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
    quitarFrames();
    OperacionesProbabilidad op = new OperacionesProbabilidad();
    op.setName("opProb");    

    jDesktopPaneBasicas.add(op);
    op.setVisible(true);
  }//GEN-LAST:event_jMenuItem1ActionPerformed

  private void quitarFrames() {
    JInternalFrame[] frames = jDesktopPaneBasicas.getAllFrames();
    int cantFrames = frames.length;

    System.out.println("cantFrames: " + cantFrames);

    if (cantFrames != 0) {
      for (int i = 0; i < cantFrames; i++) {
        jDesktopPaneBasicas.remove(0);
      }
    }

    revalidate();
    repaint();
  }

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new Principal().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JDesktopPane jDesktopPaneBasicas;
  private javax.swing.JMenu jMenu1;
  private javax.swing.JMenu jMenu2;
  private javax.swing.JMenuBar jMenuBar1;
  private javax.swing.JMenuItem jMenuItem1;
  private javax.swing.JMenuItem jMenuItemBasicas;
  private javax.swing.JMenuItem jMenuItemOtros;
  // End of variables declaration//GEN-END:variables
}
